version: '3.8'

services:
  postgres:
    build: .
    container_name: meu_postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  node:
    build:
      context: ./src
    container_name: meu_node_container
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_NAME: meu_banco
      DB_PASSWORD: root
      DB_USER: root
      PORT: 3001
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
